export const actions = {
	user: {
		LOGIN_START: 'LOGIN_START',
		LOGIN_SUCCESS: 'LOGIN_SUCCESS',
		LOGIN_FAIL: 'LOGIN_FAIL'
	},
	items: {
		FETCHING_START: 'FETCHING_START',
		FETCHING_SUCCESS: 'FETCHING_SUCCESS',
		FETCHING_FAIL: 'FETCHING_FAIL',
		ADD_LISTING: 'ADD_LISTING',
		UPDATE_LISTING: 'UPDATE_LISTING',
		DELETE_LISTING: 'DELETE_LISTING'
	}
};
